http:
  public_base: "https://mas-service-production.up.railway.app"
  listeners:
    - name: web
      binds:
        - address: "0.0.0.0:8080"
      proxy_protocol: false
      resources:
        - name: discovery
        - name: human
        - name: oauth
        - name: compat
        - name: graphql
        - name: assets

database:
  uri: "${{Postgres.DATABASE_URL}}"

upstream_oauth2:
  endpoint: "https://synapse-production-e979.up.railway.app/_synapse/oidc/callback"
  registration_shared_secret: "4578b92c30adf6e1"

secrets:
  encryption: "m8s1aH7B7eX1yq3f0h2mV7vS5Hkq3V6Z4NQvZp5l+0Y="
  keys:
    - kid: "default"
      key: "y+1d9pVf2K3n4qk7Q8u3dL2m5s6t7v8w9x0y1z2a3b4="

email:
  from: '"Matrix" <noreply@synapse-production-e979.up.railway.app>'
  reply_to: '"Matrix Support" <support@synapse-production-e979.up.railway.app>'
  transport: blackhole
