[server]
base = "{{MAS_BASE_URL}}"

[database]
uri = "{{MAS_DB_URL}}"

[synapse]
endpoint = "{{MAS_SYNAPSE_URL}}"

[crypto]
encryption_key = "{{MAS_ENCRYPTION_KEY}}"

[oauth]
client_secret = "{{MAS_OIDC_SECRET}}"
issuer = "{{MAS_BASE_URL}}"